### ISSUE TITLE
Lazy-loading of bill list

### ISSUE THREAD

**Issue by simonspa** [eneiluj/cospend-nc#11]
I have a long-running project with many bills (several hundred so far) in it and loading of the project page starts to become a bit slow. It looks like Cospend is loading all bills at once when selecting the project -  would it be possible to just load the top few and reload if the user is actually scrolling?

In the photos app they use https://github.com/tangbc/vue-virtual-scroll-list if I remember correctly, so maybe this would be an option here, too?

The reason I'm suggesting this is that I doubt it is very common to scroll down to the very first bill of the list - but it *is* very common to open a project for adding a new bill :).

**Comment by eneiluj** [comment]
It's been a long time I want to implement that and I feel less lazy these days. It's also much easier to do it since the UI was rewritten in Vue. So it's almost done. I use [vue-infinite-loading](https://github.com/PeachScript/vue-infinite-loading) which required less changes than vue-virtual-scroll-list (items, data, wrapping components etc...).

I had to refactor the sql queries to get bills to keep a good performance when we get them all and yet be able to filter and have an offset.

Im' very interested by your feedback obviously :grin:.

Some other news: It is now possible to select multiple bills and affect them a category or delete them. If you can play with it...
Next release is gonna be big!

**Comment by simonspa** [comment]
Great, this works like a charm! Just compared: my test project contains 720 bills, with the previous version just clicking on the project, the page took 7sec to load. Now wit the new version it's down to nothing and scrolling in the bill list is snappy.

Also, the multi-select option is great - I'd change the field titles to "assign category" and "assign payment mode" though.

**Comment by eneiluj** [comment]
> I'd change the field titles to "assign category" and "assign payment mode" though.

Done, thanks for the suggestion!

Progressive loading was not so much to do and it's freakin' fast now.
