### ISSUE TITLE
Repeated php error

### ISSUE THREAD

**Issue by daniel1v** [eneiluj/cospend-nc#121]
I am getting the following error several times per day:

```
Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/cospend/lib/Controller/PageController.php#921
/var/www/nextcloud/apps/cospend/lib/Controller/PageController.php - line 921:

OC\Log\ErrorHandler::onError()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Cospend\Controller\PageController->apiGetProjectInfo()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1006:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:

OC::handleRequest()
```

Nextcloudpi 1.46.7
Nextcloud 22.2.2

**Comment by eneiluj** [comment]
Thanks for the issue. This is a stupid mistake that thankfully didn't affect the app.
It's now fixed. I found another similar one when checking the password when using an old guest link.

v1.4.4-1-nightly is out. [Install instructions](https://github.com/eneiluj/cospend-nc/#nightly)
Could you check everything still works fine and the warning is gone in the logs?
Otherwise you can just wait for the next release which is coming soon.

**Comment by daniel1v** [comment]
With the latest nightly, the issue seems to be gone. Thank you for the great support!
