### ISSUE TITLE
Feature: Project Settlement for Time Range

### ISSUE THREAD

**Issue by simonspa** [eneiluj/cospend-nc#14]
It would be nice to allow to select a time range when adding a project settlement. This would enable for example a monthly settlement of a project without having to do the settlement exactly on the last day of the month before adding any new bills.

**Comment by eneiluj** [comment]
I see the point of doing a settlement "until a precise date". It means that whatever has been done after a specific date, you want balances to be brought to 0 at a certain point.

But I don't get it with a "time range". The point of settling is to bring everybody's balance to 0. If you don't do consider all bills from the start, it won't really settle. Am I missing something?

Anyway, I'll certainly do it after next release. To be continued.

**Comment by simonspa** [comment]
I think that's what I meant to say :rofl: Having an end date until which all bills should be settled would be exactly what I had in mind. Setting the default value to the current date (always to the end of the day) would even prevent from adding additional clicks to the settlement compared to now.

**Comment by eneiluj** [comment]
It's available in master.

So the max date is used to filter bills when getting the settlement plan, applying the plan and exporting the plan. If max date is set, bills created by auto settlement are dated one second before the max date (so that it's settled at the precise max date :grin:). If max date is not set, all bills are considered.

There are 3 buttons to make date selection faster:
* set to beginning of current day
* set to beginning of current week
* set to beginning of current month

> always to the end of the day

I think it make more sense to ask for a settlement in the past with these buttons.

What do you think of all that?
Cheers

**Comment by simonspa** [comment]
Works really nicely! The only thing I would maybe change is that all three buttons have the same icon:

**Comment by eneiluj** [comment]
Yeah the buttons are not definitive, that's for sure. They could have different colors...different sizes...different icons (or unicode characters). No nice idea on my side neither :grin:.

We've got time to choose.

Thanks for the feedback!

**Comment by eneiluj** [comment]
Feel free to reopen if needed.
