### ISSUE TITLE
Cannot import project from SplitWise

### ISSUE THREAD

**Issue by iluvatyr** [eneiluj/cospend-nc#159]
Hello, I wanted to go and import from Splitwise as advertised. Went to Splitwise, pressed export, copied the export.csv to nextcloud and from there went to the cospend app to import it into a new project. Unfortunately, it says the csv is malformed and cannot be imported. 
Has something changed or why isnt this possible?

**Comment by eneiluj** [comment]
Hi, Thanks for the bug report. Maybe Splitwise changed their export format. Maybe there is a bug in Cospend :grin:. If you provide an example file I can debug that and fix Cospend import process.

**Comment by eneiluj** [comment]
Thanks for the file. Splitwise had the strange idea to translate the csv column names... So they can't be predicted unless we know their sources... Even then, translations are not permanent, they can change.

There is no obvious good solution to fix the import process in Cospend... If the column order is always the same we can use that to identify them instead of their names.

Immediate solution for you: rename the columns in your file:

`Datum,Beschreibung,Kategorie,Kosten,Währung,Person3,Person1,Person2`

becomes

`Date,Description,Category,Cost,Currency,Person3,Person1,Person2`

A small fix to the import process was still needed. If you can try v1.4.9-4-nightly, great. If not, next release is coming soon and will include the fix. You will still need to bring the column names back to English :grin:.

**Comment by iluvatyr** [comment]
It worked to import the Splitwise file after upgrading to nightly and changing to english names like you said. I don't even understand why the language there is in German since my device language aswell as my app language is english. Pretty weird.

Thank you for solving this issue and thank you for doing this awesome project.

**Comment by iluvatyr** [comment]
Hello, I'm sorry I answer just now,

So thank you for your time on fixing this. From what you are saying, it sounds like everything is fixed now.
Did you implement this also in the latest nightly version?
I ran "occ app:update --allow-unstable cospend", restarted nextcloud, and imported the export.csv, but the values are just like in my previous comment, where everything was still unfixed.

**Comment by eneiluj** [comment]
> Did you implement this also in the latest nightly version?

Yes, v1.4.9-5-nightly

Are you sure it upgraded to v1.4.9-5-nightly?

I just tried again with your original file (after fixing the column names) and it works fine.

**Comment by iluvatyr** [comment]
I'm sorry I could not try since my internet providers cable was destroyed by some construction works and my server is just back online now - horrible days.

Anyways, I uninstalled cospend and reinstalled and then updated it with nightly and it works. So again, thank you very much for this awesome support!
