### ISSUE TITLE
possible to use it for a single person or for a family?

### ISSUE THREAD

**Issue by jakobroehrl** [eneiluj/cospend-nc#21]
Hi, 
is it possible to use it for a single person or for a family?
I don't want to split the costs.
Thanks!

**Comment by eneiluj** [comment]
Hi,

This app's purpose is to share the expenses :grin: so I would say it's maybe not the tool you are looking for. Let's see if it's true.

It's possible to use it for a single person: even if there is a minimum of 2 members per project, just have a real one and a fake one. Then add bills paid by you for you. You'll be able to track your expenses. Some of the statistics will still be useful (like on categories) and some will be useless because it's about sharing expenses :wink:

What do you mean by "for a family"? If you mean the expenses are not to be shared inside the family, then you can use Cospend like described before, like if there was just one member.

You can also add a project member per family member and ignore never use the settlement (if you don't want people to reimburse themselves). Then you still have expense tracking and some stats.

**Comment by jakobroehrl** [comment]
Thank you, I will try it.
