### ISSUE TITLE
Payer and receiver interchanged in statistics

### ISSUE THREAD

**Issue by helasz** [eneiluj/cospend-nc#3]
After creating successfully a bill stating X pays to Y amount A of money in checking the statistics I find that X (who has payed) has positive balance and instead Y (who received the payment) has a negative one (the sum obviously matches). See attached screendshot. 
I am using Nextcloud 19.0.4 and Cospend 1.0.5, MySQL database, Firefox 81.0.2 (x64).
[cospend_issue.pdf](https://github.com/eneiluj/cospend-nc/files/5431836/cospend_issue.pdf)

**Comment by eneiluj** [comment]
Hi, the balance does not represent the amount of money someone has. Cospend's purpose is not to track money transactions between members. It is rather to keep track of what has been spent in a group of people and who owes the group and who the group owes. A positive balance means that, in average, regardless of who did what, the group owes the member.

The bill payer is the person who actually spends the money for something (fruits for example). The owers are the persons for which the money was spent (maybe someone is absent and will not eat the fruits so it's not an ower for this bill). The goal is to simplify money management in a group. When someone leaves the group, you know exactly how much money this person should give or receive to get even with the others. It does not even matter who the money is given to or who should give it, because the goal is just to bring the balance of the one who leaves to zero.

All shared budget managers I know work like that.
Is it clearer now?

**Comment by helasz** [comment]
Hi Julien, 

Thanks for your - amazingly speedy - clarification. I
see the point now. 

Do I need to close somehow the issue on Github?


Best regards, 

László 

Fri, 23 Oct 2020 17:03:21 -0700 időpontban
Julien Veyssier írta: 

>   
> 
> Hi, the balance does not represent the
amount of money someone has. Cospend's purpose is not to track money
transactions between members. It is rather to keep track of what has
been spent in a group of people and who owes the group and who the group
owes. A positive balance means that, in average, regardless of who did
what, the group owes the member. 
> 
> The bill payer is the person who
actually spends the money for something (fruits for example). The owers
are the persons for which the money was spent (maybe someone is absent
and will not eat the fruits so it's not an ower for this bill). The goal
is to simplify money management in a group. When someone leaves the
group, you know exactly how much money this person should give or
receive to get even with the others. It does not even matter who the
money is given to or who should give it, because the goal is just to
bring the balance of the one who leaves to zero. 
> 
> All shared budget
managers I know work like that.
> Is it clearer now? 
> 
> —
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [1], or unsubscribe [2].

 


Links:
------
[1]
https://github.com/eneiluj/cospend-nc/issues/3#issuecomment-715637952
[2]

**Comment by eneiluj** [comment]
You're welcome!
